### ISSUE TITLE
New Lines - TMB tool issue?

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/tempe#7]
https://github.com/tgen/tempe/blob/ab7f96495771a9c09dcf90016a2c395614545f3d/modules/metrics/mutation_burden.jst#L98-L99

@bryce-turner @ChristopheLegendre Why are we adding these two new lines in the pipeline script? Is there an issue in the TMB code that needs to be resolved? Seems like a band-aid fix

**Comment by bryce-turner** [comment]
This is because the downstream stats2json expects 2 new lines at the end of the file (might have actually been that the last line doesn't include \n and then stats2json expects an empty \n line at the end of the file) . I don't think there necessarily was a limitation of TMB, but @ChristopheLegendre mentioned that this script has been used previously by other users and we opted to not potentially break existing scripts that might have been generated based on the existing output.

Closing this, but no worries if we need to reopen and adjust the code.

**Comment by PedalheadPHX** [comment]
So the issue is stats2json?, my argument is either stats2json needs an update or the TMB output does, adding new lines in the pipeline is a band-aid

**Comment by bryce-turner** [comment]
Created pull request on TMB repository

**Comment by bryce-turner** [comment]
Auto closed after PR was accepted and merged on the tgen_mutation_burden repo, but these lines were explicitly changed on commit a722372
